remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Wes Reis
description: Practice portfolio.
show_downloads: yes
logo: assets/profile.jpg
